#!/bin/sh
#
# Copy JSBSim source into the FlightGear source tree
#
# Assumes you've set the environment variables:
#  FG_SRC=~/FlightGear/src
#  FG_ROOT=~/FlightGear

INSTALL="cp -uv"

# Gather or default settings. Assumes the current directory is
# a JSBSim working directory, with FlightGear and fgfsbase siblings
if [ "x$FG_SRC" = "x" ]; then
	FG_SRC=`pwd`/../FlightGear/src
	echo "Defaulting FG_SRC to $FG_SRC"
fi

if [ "x$FG_ROOT" = "x" ]; then
	FG_ROOT=`pwd`/../FlightGear
	echo "Defaulting FG_ROOT to $FG_ROOT"
fi

# Check directories exist
if [ ! -d "$FG_SRC/FDM/JSBSim/filtersjb" ]; then
	echo "No $FG_SRC/FDM/JSBSim/filtersjb directory";
	mkdir $FG_SRC/FDM/JSBSim/filtersjb
	exit;
fi

if [ ! -d "$FG_ROOT/Engine" ]; then
	echo "No $FG_ROOT/Engine directory";
	exit;
fi

for i in c172 X15 shuttle c310 c182 x24b; do
    if [ ! -d "$FG_ROOT/Aircraft/$i" ]; then
	echo "No $FG_ROOT/Aircraft/$i";
	exit;
    fi
done

# Perform the copy
$INSTALL JSBSim.[ch]xx $FG_SRC/FDM/

for i in FG*.cpp; do
    $INSTALL $i $FG_SRC/FDM/JSBSim/
done
    
for i in FG*.h; do
    $INSTALL $i $FG_SRC/FDM/JSBSim/
done    

$INSTALL filtersjb/*.cpp $FG_SRC/FDM/JSBSim/filtersjb/
$INSTALL filtersjb/*.h $FG_SRC/FDM/JSBSim/filtersjb/
$INSTALL engine/*.xml $FG_ROOT/Engine/
$INSTALL aircraft/c172/c172.xml $FG_ROOT/Aircraft/c172/
$INSTALL aircraft/X15/X15.xml $FG_ROOT/Aircraft/X15/
$INSTALL aircraft/shuttle/shuttle.xml $FG_ROOT/Aircraft/shuttle/
$INSTALL aircraft/c310/c310.xml $FG_ROOT/Aircraft/c310/
$INSTALL aircraft/c182/c182.xml $FG_ROOT/Aircraft/c182/
$INSTALL aircraft/x24b/x24b.xml $FG_ROOT/Aircraft/x24b/
