#!/bin/sh

if [ x$1 = x ]; then
   echo "Usage: $0 [FlightGear source path (where is AUTHORS)]"
   exit;
fi

NEW_FILES=
REMOVED_FILES=
CUR_DIR=`pwd`
CP="cp -p"

for n in `find . -type f -name 'JSBSim.[ch]xx' -o -name 'FG*.cpp' -o -name 'FG*.h`; do

   if [ -f $1/src/FDM/JSBSim/$n ]; then

      NUM=`diff $n $1/src/FDM/JSBSim/$n | grep -e ">" -e "<" | wc -l`;
      NUM_ID=`diff $n $1/src/FDM/JSBSim/$n | grep -e ">" -e "<" | grep "\$Id:" | wc -l`;

      if [ ! $NUM -eq $NUM_ID ]; then
         echo "$1/src/FDM/JSBSim/$n";
         $CP $n $1/src/FDM/JSBSim/$n
      fi;

   else

      NEW_FILES="$NEW_FILES $n";

   fi;

done

if [ "x$NEW_FILES" != "x" ]; then
   echo
   echo "The following files where not found in the FlightGear source"
   echo "directory:"
   echo $NEW_FILES
   echo
fi;

cd $1/src/FDM/JSBSim;
for n in `find . -type f -name 'JSBSim.[ch]xx' -o -name 'FG*.cpp' -o -name 'FG*.h`; do

    if [ ! -f $CUR_DIR/$n ]; then
        REMOVED_FILES="$REMOVED_FILES $n";
    fi;

done
cd $CUR_DIR

if [ "x$REMOVED_FILES" != "x" ]; then
    echo
    echo "The following files where found in the FlightGear source"
    echo "directory but are not present in the JSBSim root directory:"
    echo $REMOVED_FILES
    echo
fi;
