#!/bin/sh

if [ x$1 = x ]; then
   echo "Usage: $0 [FlightGear source path (where is AUTHORS)]"
   exit;
fi

NEW_FILES=

for n in `find . -type f -name 'JSBSim.[ch]xx' -o -name 'FG*.cpp' -o -name 'FG*.h`; do

   if [ -f $1/src/FDM/JSBSim/$n ]; then

      NUM=`diff $n $1/src/FDM/JSBSim/$n | grep -e ">" -e "<" | wc -l`;
      NUM_ID=`diff $n $1/src/FDM/JSBSim/$n | grep -e ">" -e "<" | grep "\$Id:" | wc -l`;

      if [ ! $NUM -eq $NUM_ID ]; then
         echo "$1/src/FDM/JSBSim/$n";
         cp -p $n $1/src/FDM/JSBSim/$n
      fi;

   else

      NEW_FILES="$NEW_FILES $n";

   fi;

done

if [ "x$NEW_FILES" != "x" ]; then
   echo "The following files where not found in the FlightGear source"
   echo "directory:"
   echo $NEW_FILES
   echo
fi;
