CC = g++
libProperties_OBJECTS = props.o

INCLUDES = -I../../

libProperties.a: $(libProperties_OBJECTS)
	-rm -f libProperties.a
	ar cru libProperties.a $(libProperties_OBJECTS)
	ranlib libProperties.a

props.o: props.cxx props.hxx
	$(CC) $(INCLUDES) $(CCOPTS) -oprops.o -c props.cxx

clean:
	-rm -f *.o
	-rm -f *.a

all:
	touch *.cxx
	make libProperties.a -fMakefile.solo

debug:
	make all CCOPTS=-g -fMakefile.solo
