blank_issues_enabled: false
contact_links:
  - name: JSBSim Community Support
    url: https://github.com/JSBSim-Team/jsbsim/discussions
    about: Submit support requests or ask your questions here.
