name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake cxxtest

      - name: Install cxxtest on macOS
        if: runner.os == 'macOS'
        run: brew install cxxtest

      - name: Install cxxtest on Windows
        if: runner.os == 'Windows'
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/cxxtest/files/cxxtest/4.4/cxxtest-4.4.zip/download" -OutFile cxxtest.zip
          Expand-Archive cxxtest.zip -DestinationPath C:\
          echo "C:\cxxtest-4.4" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: cmake .. -DBUILD_TESTS=ON

      - name: Build
        working-directory: ./build
        run: make

      - name: Run tests
        working-directory: ./build
        run: |
          ./tests/unit_tests/InterpolationTest1

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-results
          path: build/Testing/Temporary/LastTest.log
